class AppStaticTextsEn{
  static const Map<String, String> texts = {
    'appName': 'Kulübe',
    'appDescription': 'Benek is a platform designed for pet owners and caregivers.',
    'error': 'Error',
    'welcomeMessage': 'Welcome to the Kulübe',
    'qrCodeDescription': 'To log in, scan the code below into the Benek application.',
    'toGetNewQrCode': 'Click the button to get a new QR code :)',
    'qrCodeExpireTime': 'This code expires in one hour!',
    'welcomeScreenWarning': 'This platform is for Benek employees! If you are not, please delete the app!',
    'searchAUser': 'Search for a User',
    'searchAPet': 'Search for a Pet',
    'homeTab': 'Main menu',
    'logsTab': 'Logs',
    'reportedTab': 'Reported',
    'filesTab': 'Folders',
    'employeesTab': 'Employees',
    'contactMessagesTab': 'Requests',
    'logoutTab': 'Log out',
    'welcome': 'Welcome',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    'noStoryMessage': 'There is no Story!',
    'userIsCareGiver': 'Caregiver',
    'userIsNotCareGiver': 'Not Caregiver',
    'regularUser': 'Unauthorized User',
    'superAdmin': 'Super Admin',
    'developer': 'Developer',
    'moderator': 'Moderator',
    'accountant': 'Accountant',
    'unauthorizedUser': 'Record Not Found',
    'pets': 'Pets',
    'usersPets': 'Pets',
    'noPetMessage': 'No Pets!',
    'notFoundMessage': 'Not Found!',
    'pastCareGiversTitle': 'Purchased Care Give Services :',
    'givenCareGivesTitle': 'Given Care Give Services :',
    'pastCareGiversEmptyMessage': 'Didn\'t Purchase Any Caregive!',
    'givenCareGivesEmptyMessage': 'Didn\'t Give Any Caregive!',
    'seeAll': 'See All',
    'startDate': 'Start Date :',
    'endDate': 'End Date :',
    'volunteer': 'Volunteer',
    'giveAuthRoleButonText': 'Give Auth Role',
    'copied': 'Copied!',
    'showOnMap': 'Show on Map',
    'punishUser': 'Punish User',
    'seeDetails': 'See Details',
    'usersMessagesTitle': 'User\'s Messages',
    'textMessageTitle': 'Sent a Message',
    'fileMessageTitle': 'Sent a File',
    'paymentOfferMessageTitle': 'Offered Payment',
    'userProfileMessageTitle': 'Sent a User Profile',
    'petProfileMessageTitle': 'Sent a Pet Profile',
    'eventMessageTitle': 'Sent an Event',
    'undefinedMessageType': 'Undefined Message Type',
    'emptyMessageBoxTitle': 'Message Box is Empty',
    'noMessage': 'No Message Yet!',
    'createdAt': 'Created At',
    'noLog': 'No Log Yet!',
    'seeUsersLogs': 'See Logs',
    'punishment': 'Punishment',
    'noPunishment': 'No Punishment Record!',
    'yearsOld': 'Years Old',
    'Female': 'Female',
    'Male': 'Male',
    'beTheFirstOneToLike': 'Be the first one to like!',
    'peopleLiked': 'People Liked',
    'justYou': 'Just You',
    'post': 'Post',
    'writeACaption': 'Write a caption...',
    'writeAComment': 'Write a comment...',
    'writeAReply': 'Write a reply...',
    'commentEmptyState': 'No Comment Yet!',
    'replyEmptyState': 'No Reply Yet!',
    'tagPetInfoCaption': 'Stories has to be about A pet! Please tag a pet!',
    'addDescriptionCaption': 'Writing a description for the Story is mandatory!',
    'invalidPath': 'Invalid File Path!',
    'invalidPathDesc': 'The file path you provided is invalid. Please check the file path and try again.',
    'enterDescFirst': 'Enter Description First!',
    'delete': 'Delete',
    'like': 'Like',
    'reply': 'Reply',
    'approveStoryDelete': 'Slide to delete story...',
    'approveCommentDelete': 'Slide to delete comment...',
    'approveReplyDelete': 'Slide to delete reply...',
    'accountInfo': 'Account Info',
    'deactivateAccount': 'Slide to deactivate your account...',
    'approveChanges' : 'Slide to save changes...',
    'youRNotACareGiverYet': 'You are not a caregiver yet!',
    'becomeACareGiverInfo': 'You have to be a caregiver to participate in any commercial activity within the app...',
    'TCNo': 'TC Identification Number',
    'enterTCNo': 'Enter your TC Identification Number...',
    'iban': 'IBAN',
    'enterIban': 'Enter your IBAN number...',
    'fullname': 'Full name and surname on the ID',
    'username': 'User name',
    'email': 'E-mail',
    'enterEmail': 'Enter your e-mail address...',
    'phoneNumber': 'Turkish phone number (without country code)',
    'enterPhoneNumber': 'Enter your phone number...',
    'edit': 'Edit',
    'uploadNewOne': 'Upload New One',
    'approveProfilePhotoDelete': 'Slide to delete profile photo...',
    'writeBio': 'Write Bio',
    'outOfTurkey': 'You have chosen a location outside of Türkiye.',
    'approveCancelChanges': 'Slide to cancel changes...',
    'save': 'Save',
    'chooseYourLocationCaption': 'Choose Your Location',
    'chooseYourLocationDesc': 'Mark your official address on the map, edit the open address and save...',
    'missingLastName': 'Please enter full name and surname!',
    'invalidEmail': 'Invalid e-mail address!',
    'approveNameChanges': 'Slide to change your name...',
    'approveEmailChanges': 'Slide to change your e-mail...',
    'approveUsernameChanges': 'Slide to change your username...',
    'approveTCNOChanges': 'Slide to change your Turkish ID Number...',
    'approveIbanChanges': 'Slide to change your IBAN number...',
    'slideToApprove': 'Slide to approve...',
    'reSendEmail': 'Resend the code',
    'missingOtpCode': 'Missing verification code!',
    'operationFailed': 'Operation failed!',
    'operationSucceeded': 'Operation succeeded!',
    'changePassword': 'Change Your Password!',
    'enterYourCurrentPassword': 'Enter your current password...',
    'newPassword': 'New Password',
    'enterYourNewPassword': 'Enter your new password',
    'passwordValidationError': 'Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one special character.',
    'forgetPassword': 'Forget your password?',
    'forgetPasswordApproveMessage': 'Slide to reset your password...',
    'resetPasswordInfo': "After this point, you will log out of the app and we will email you a new password. If you remember your old password before using the new temporary password, you do not need to use the temporary password we sent you.",
    'resetPasswordAndLogout': "Reset password and logout...",
    'resetPassword': "Reset Password",
    'becomeCareGiverMissingIban': "To become a caregiver, you must enter your IBAN number, which will receive your payment!",
    'becomeCareGiverMissingPhone': "To become a caregiver, you must enter your phone number!",
    'becomeCareGiverMissingEmail': "To become a caregiver, you must enter your email address!",
    'becomeCareGiverMissingNationalIdentityNumber': "To become a caregiver, you must be a Turkish citizen and you must enter your Turkish ID number!",
    'becomeCareGiverChooseYourLocationCaption': "To become a caregiver, mark your official address on the map, edit the full address and save...",
    'youBecameACareGiver': 'You have become a caregiver!',
    'YouCantEditYourAuth': "You can't edit your own authorization!",
  };
}