class AppStaticTextsTr{
  static const Map<String, String> texts = {
    'appName': 'Kulübe',
    'appDescription': 'Benek, evcil hayvan sahipleri ve bakıcıları için tasarlanmış bir platformdur.',
    'error': 'Hata',
    'welcomeMessage': "Kulübe\''ye Hoş Geldin",
    'qrCodeDescription': 'Giriş yapmak için aşağıdaki kodu Benek uygulamasına okut.',
    'toGetNewQrCode': 'Yeni bi QR kod almak için butona tıkla :)',
    'qrCodeExpireTime': 'Bu kodun süresi, bir saat içinde dolar!',
    'welcomeScreenWarning': 'Bu platform Benek çalışanları içindir! Eğer değilsen, lütfen uygulamayı sil!',
    'searchAUser': 'Bir Kullanıcı Ara',
    'searchAPet': 'Bir Evcil Hayvan Ara',
    'homeTab': 'Ana Menü',
    'logsTab': 'Loglar',
    'reportedTab': 'Bildirilenler',
    'filesTab': 'Dosyalar',
    'employeesTab': 'Çalışanlar',
    'contactMessagesTab': 'Talepler',
    'logoutTab': 'Çıkış Yap',
    'welcome': 'Hoş Geldin',
    'today': 'Bugün',
    'monday': 'Pazartesi',
    'tuesday': 'Salı',
    'wednesday': 'Çarşamba',
    'thursday': 'Perşembe',
    'friday': 'Cuma',
    'saturday': 'Cumartesi',
    'sunday': 'Pazar',
    'january': 'Ocak',
    'february': 'Şubat',
    'march': 'Mart',
    'april': 'Nisan',
    'may': 'Mayıs',
    'june': 'Haziran',
    'july': 'Temmuz',
    'august': 'Ağustos',
    'september': 'Eylül',
    'october': 'Ekim',
    'november': 'Kasım',
    'december': 'Aralık',
    'noStoryMessage': 'Hiç Anı Yok!',
    'userIsCareGiver': 'Bakıcı',
    'userIsNotCareGiver': 'Bakıcı Değil',
    'regularUser': 'Yetkisiz Kullanıcı',
    'superAdmin': 'Super Admin',
    'developer': 'Geliştirici',
    'moderator': 'Modaratör',
    'accountant': 'Muhasebe',
    'unauthorizedUser': 'Kayıt Bulunamadı',
    'pets': 'Evcil Hayvanlar',
    'usersPets': 'Evcil Hayvanları',
    'allOwners': 'Bütün Sahipleri',
    'noPetMessage': 'Evcil Hayvanı Yok!',
    'notFoundMessage': 'Bulunamadı!',
    'pastCareGiversTitle': 'Aldığı Bakım Hizmetleri :',
    'givenCareGivesTitle': 'Verdiği Bakım Hizmetleri :',
    'pastCareGiversEmptyMessage': 'Hiç Bakım Almadı!',
    'givenCareGivesEmptyMessage': 'Hiç Bakım Vermedi!',
    'seeAll': 'Tümünü Gör',
    'startDate': 'Başlangıç Tarihi :',
    'endDate': 'Bitiş Tarihi :',
    'date': "Tarih :",
    'volunteer': 'Gönüllü',
    'giveAuthRoleButonText': 'Yetki Ver',
    'copied': 'Kopyalandı!',
    'showOnMap': 'Haritada Göster',
    'punishUser': 'Cezalandır',
    'seeDetails': 'Detayları Gör',
    'usersMessagesTitle': 'Kullanıcının Mesajları',
    'textMessageTitle': 'Mesaj Gönderdi',
    'fileMessageTitle': 'Dosya Gönderdi',
    'paymentOfferMessageTitle': 'Ödeme Teklif Etti',
    'userProfileMessageTitle': 'Kullanıcı Profili Gönderdi',
    'petProfileMessageTitle': 'Hayvan Profili Gönderdi',
    'eventMessageTitle': 'Bir Etkinlik Paylaştı',
    'undefinedMessageType': 'Tanımlanamayan Mesaj Türü',
    'emptyMessageBoxTitle' : 'Mesaj Kutusu Boş',
    'noMessage': 'Hiç Mesaj Yok!',
    'createdAt': 'Tarihinde Oluşturuldu',
    'noLog': 'Hiç Log Yok!',
    'seeUsersLogs': 'Loglarını Gör',
    'punishment': 'Ceza',
    'noPunishment': 'Ceza Kaydı Yok!',
    'yearsOld': 'Yaşında',
    'Female': 'Dişi',
    'Male': 'Erkek',
    'beTheFirstOneToLike': 'İlk Beğenen Sen Ol!',
    'peopleLiked': 'Kişi Beğendi',
    'justYou': 'Sadece Sen',
    'post': 'Gönder',
    'writeACaption': 'Bir açıklama yaz...',
    'writeAComment': 'Bir yorum yaz...',
    'writeAReply': 'Bir yanıt yaz...',
    'writeAMessage': 'Bir mesaj yaz...',
    'commentEmptyState': 'Hiç Yorum Yok!',
    'replyEmptyState': 'Hiç Yanıt Yok!',
    'tagPetInfoCaption': 'Anılar bir evcil hayvanlarla ilgilidir! Lütfen bir evcil hayvan etiketleyin!',
    'addDescriptionCaption': 'Anı için açıklama yazmak zorunludur!',
    'invalidPath': 'Geçersiz Dosya Yolu!',
    'invalidPathDesc': 'Dosya yolu geçersizdir. Lütfen Dosya yolunu kontrol edip tekrar deneyin.',
    'enterDescFirst': 'Önce Açıklama Girin!',
    'delete': 'Sil',
    'like': 'Beğeni',
    'reply': 'Yanıt',
    'approveStoryDelete': 'Anıyı silmek için kaydır...',
    'approveCommentDelete': 'Yorumu silmek için kaydır...',
    'approveReplyDelete': 'Yanıtı silmek için kaydır...',
    'accountInfo': 'Hesap Bilgileri',
    'deactivateAccount': 'Hesabını deaktive etmek için kaydır...',
    'approveChanges': 'Değişiklikleri kaydetmek için kaydır...',
    'youRNotACareGiverYet': 'Henüz bir bakıcı değilsiniz!',
    'becomeACareGiverInfo': 'Uygulama içerisinde, herhangi bir ticari faaliyete katılabilmek için bakıcı olmalısın...',
    'TCNo': 'TC kimlik numarası',
    'enterTCNo': 'TC kimlik numaranı gir...',
    'iban': 'IBAN',
    'enterIban': 'IBAN numaranı gir...',
    'fullname': 'Kimlikte yer alan tam isim ve soyisim',
    'username': 'Kullanıcı Adı',
    'email': 'E-posta',
    'enterEmail': 'E-posta adresini gir...',
    'phoneNumber': 'Türk telefon numarası (ülke kodu olmadan)',
    'enterPhoneNumber': 'Telefon numaranı gir...',
    'edit': 'Düzenle',
    'uploadNewOne': 'Yenisini Yükle',
    'approveProfilePhotoDelete': 'Profil Resmini silmek için kaydır...',
    'writeBio': 'Biyografi Yaz',
    'outOfTurkey': 'Türkiye sınırları dışında bir konum seçtiniz.',
    'approveCancelChanges': 'Değişiklikleri iptal etmek için kaydır...',
    'save': 'Kaydet',
    'chooseYourLocationCaption': 'Konumunuzu seçin',
    'chooseYourLocationDesc': 'Haritada, ikametgah adresinizi işaretleyin, açık adresi düzenleyin ve kaydedin...',
    'missingLastName': 'Lütfen tam isim soyisim girin!',
    'invalidEmail': 'Geçersiz e-posta adresi!',
    'invalidPhoneNumber': 'Geçersiz telefon numarası!',
    'approveNameChanges': 'İsmini değiştirmek için kaydır...',
    'approveEmailChanges': 'E-Postanı değiştirmek için kaydır...',
    'approvePhoneNumberChanges': 'Telefon numaranı değiştirmek için kaydır...',
    'approveUsernameChanges': 'Kullanıcı Adını değiştirmek için kaydır...',
    'approveTCNOChanges': 'TC Kimlik Numarasını değiştirmek için kaydır...',
    'approveIbanChanges': 'IBAN numarasını değiştirmek için kaydır...',
    'slideToApprove': 'Onaylamak için kaydır..',
    'reSendEmail': 'Kodu tekrar gönder',
    'missingOtpCode': 'Doğrulama kodu eksik!',
    'operationFailed': 'İşlem başarısız!',
    'operationSucceeded': 'İşlem başarılı!',
    'changePassword': 'Şifreni Değiştir!',
    'enterYourCurrentPassword': 'Mevcut şifrenizi girin...',
    'newPassword': 'Yeni Şifre',
    'enterYourNewPassword': 'Yeni şifrenizi girin',
    'passwordValidationError': 'Şifreniz en az 8 karakter uzunluğunda olmalı ve en az bir büyük harf, bir küçük harf, bir rakam ve bir özel karakter içermelidir.',
    'forgetPassword': 'Şifreni mi unuttun?',
    'forgetPasswordApproveMessage': 'Şifreni sıfırlamak için kaydır...',
    'resetPasswordInfo': "Bu noktadan sonra uygulamadan çıkış yapacaksın ve e-postana yeni bir şifre göndereceğiz. Eğer, bahsi geçen yeni, geçici şifreyi kullanmadan, eski şifreni hatırlarsan, gönderdiğimiz geçici şifreyi kullanman gerekmez.",
    'resetPasswordAndLogout': "Şifreyi sıfırla ve çıkış yap...",
    'resetPassword': "Şifreni Sıfırla",
    'becomeCareGiverMissingIban': "Bakıcı Olabilmek için, ödeme alacağın, IBAN numaranı girmelisin!",
    'becomeCareGiverMissingPhone': "Bakıcı Olabilmek için, telefon numaranı girmelisin!",
    'becomeCareGiverMissingEmail': "Bakıcı Olabilmek için, e-posta adresini girmelisin!",
    'becomeCareGiverMissingNationalIdentityNumber': "Bakıcı Olabilmek için, TC vatandaşı olmalı ve TC kimlik numaranı girmelisin! (Vergi işlemleri için...",
    'becomeCareGiverChooseYourLocationCaption': "Bakıcı olabilmek için, resmi adresini haritada işaretle, açık adresi düzenle ve kaydet...",
    'youBecameACareGiver': "Artık sen de bir Benek'li bakıcısın :)",
    'YouCantEditYourAuth': "Kendi yetkini düzenleyemezsin!",
    'enterPunishmentDesc': "Cezalandırma sebebini gir...",
    'youCantPunishYourself': "Kendine ceza puanı veremezsin!",
    'averageRating': "Ortalama puan",
    'totalVote': "Toplam oy sayısı",
    'primaryOwner': "Ana Sahip",
    'turnBackToSelectedUser': "Seçili kullanıcıya geri dön...",
    'searchChat': "Mesaj Ara...",
    'enterChatDesc': "Sohbet Açıklaması Girin...",
    'leaveChat': "Sohbetten ayrılmak için kaydır...",
    'missingUser': "Bulunmayan Kullanıcı",
    'addMembers': "Üye ekle...",
    'selectAMember': "Bir üye seç",
    'enterExcuse': "Mazeret girin...",
    'sendExcuse': "Şikayeti haklı bul ve mazereti gönder!",
    'approveAcceptingReport': "Şikayeti kabul etmek için kaydır...",
    'cancelReport': "Şikayeti iptal et",
    'totalMoneyOnPool': "Havuzdaki toplam para",
    'profit': "Kar",
    'customersShare': "Müşteri Payı",
    'customersTax': "Müşteri Vergisi",
    'careGiverAdress': "Bakıcı Adresi :",
    'careGiver': "Bakıcı :",
    'customer': "Müşteri :",
  };
}