class AppStaticTextsTr{
  static const Map<String, String> texts = {
    'appName': 'Kulübe',
    'appDescription': 'Benek, evcil hayvan sahipleri ve bakıcıları için tasarlanmış bir platformdur.',
    'welcomeMessage': 'Kulübe\'ye Hoş Geldin',
    'qrCodeDescription': 'Giriş yapmak için aşağıdaki kodu Benek uygulamasına okut.',
    'toGetNewQrCode': 'Yeni bi QR kod almak için butona tıkla :)',
    'qrCodeExpireTime': 'Bu kodun süresi, bir saat içinde dolar!',
    'welcomeScreenWarning': 'Bu platform Benek çalışanları içindir! Eğer değilsen, lütfen uygulamayı sil!',
    'searchAUser': 'Bir Kullanıcı Ara',
    'homeTab': 'Ana Menü',
    'logsTab': 'Loglar',
    'reportedTab': 'Bildirilenler',
    'filesTab': 'Dosyalar',
    'employeesTab': 'Çalışanlar',
    'contactMessagesTab': 'Talepler',
    'logoutTab': 'Çıkış Yap',
    'welcome': 'Hoş Geldin',
    'monday': 'Pazartesi',
    'tuesday': 'Salı',
    'wednesday': 'Çarşamba',
    'thursday': 'Perşembe',
    'friday': 'Cuma',
    'saturday': 'Cumartesi',
    'sunday': 'Pazar',
    'january': 'Ocak',
    'february': 'Şubat',
    'march': 'Mart',
    'april': 'Nisan',
    'may': 'Mayıs',
    'june': 'Haziran',
    'july': 'Temmuz',
    'august': 'Ağustos',
    'september': 'Eylül',
    'october': 'Ekim',
    'november': 'Kasım',
    'december': 'Aralık',
    'noStoryMessage': 'Hiç Anı Yok!',
    'userIsCareGiver': 'Bakıcı',
    'userIsNotCareGiver': 'Bakıcı Değil',
    'regularUser': 'Yetkisiz Kullanıcı',
    'superAdmin': 'Super Admin',
    'developer': 'Geliştirici',
    'moderator': 'Modaratör',
    'accountant': 'Muhasebe',
    'unauthorizedUser': 'Kayıt Bulunamadı',
    'pets': 'Evcil Hayvanlar',
    'usersPets': 'Evcil Hayvanları',
    'noPetMessage': 'Evcil Hayvanı Yok!',
    'notFoundMessage': 'Bulunamadı!',
    'pastCareGiversTitle': 'Aldığı Bakım Hizmetleri :',
    'givenCareGivesTitle': 'Verdiği Bakım Hizmetleri :',
    'pastCareGiversEmptyMessage': 'Hiç Bakım Almadı!',
    'givenCareGivesEmptyMessage': 'Hiç Bakım Vermedi!',
    'seeAll': 'Tümünü Gör',
    'startDate': 'Başlangıç Tarihi :',
    'endDate': 'Bitiş Tarihi :',
    'volunteer': 'Gönüllü',
    'giveAuthRoleButonText': 'Yetki Ver',
    'copied': 'Kopyalandı!',
    'showOnMap': 'Haritada Göster',
    'punishUser': 'Cezalandır',
    'seeDetails': 'Detayları Gör',
  };
}