class AppStaticTextsEn{
  static const Map<String, String> texts = {
    'appName': 'Kulübe',
    'appDescription': 'Benek is a platform designed for pet owners and caregivers.',
    'welcomeMessage': 'Welcome to the Kulübe',
    'qrCodeDescription': 'To log in, scan the code below into the Benek application.',
    'toGetNewQrCode': 'Click the button to get a new QR code :)',
    'qrCodeExpireTime': 'This code expires in one hour!',
    'welcomeScreenWarning': 'This platform is for Benek employees! If you are not, please delete the app!',
    'searchAUser': 'Search for a User',
    'homeTab': 'Main menu',
    'logsTab': 'Logs',
    'reportedTab': 'Reported',
    'filesTab': 'Folders',
    'employeesTab': 'Employees',
    'contactMessagesTab': 'Requests',
    'logoutTab': 'Log out',
    'welcome': 'Welcome',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    'noStoryMessage': 'There is no Story!',
    'userIsCareGiver': 'Caregiver',
    'userIsNotCareGiver': 'Not Caregiver',
    'regularUser': 'Unauthorized User',
    'superAdmin': 'Super Admin',
    'developer': 'Developer',
    'moderator': 'Moderator',
    'accountant': 'Accountant',
    'unauthorizedUser': 'Record Not Found',
    'pets': 'Pets',
    'usersPets': 'Pets',
    'noPetMessage': 'No Pets!',
    'notFoundMessage': 'Not Found!',
    'pastCareGiversTitle': 'Purchased Care Give Services :',
    'givenCareGivesTitle': 'Given Care Give Services :',
    'pastCareGiversEmptyMessage': 'Didn\'t Purchase Any Caregive!',
    'givenCareGivesEmptyMessage': 'Didn\'t Give Any Caregive!',
    'seeAll': 'See All',
    'startDate': 'Start Date :',
    'endDate': 'End Date :',
    'volunteer': 'Volunteer',
    'giveAuthRoleButonText': 'Give Auth Role',
    'copied': 'Copied!',
    'showOnMap': 'Show on Map',
    'punishUser': 'Punish User',
    'seeDetails': 'See Details',
  };
}